import { Document, Page, Text, View, StyleSheet, renderToBuffer } from "@react-pdf/renderer";
import type { Report, ServiceRequest, ServiceCategory } from "@prisma/client";

const styles = StyleSheet.create({
  page: { padding: 32, fontSize: 11, fontFamily: "Helvetica" },
  header: { marginBottom: 16, borderBottom: "2px solid #1A8C6F", paddingBottom: 8 },
  brand: { fontSize: 20, fontWeight: 700, color: "#0F5C48" },
  subtitle: { fontSize: 10, color: "#4A6B63", marginTop: 2 },
  section: { marginBottom: 12 },
  sectionTitle: { fontSize: 13, fontWeight: 700, marginBottom: 6, color: "#1A2E29" },
  row: { flexDirection: "row", marginBottom: 3 },
  label: { width: 160, color: "#4A6B63" },
  value: { flex: 1, color: "#1A2E29" },
  checklistItem: { marginBottom: 4, flexDirection: "row" },
  bullet: { width: 12 },
  footer: { marginTop: 24, fontSize: 9, color: "#8AADA5", textAlign: "center" },
});

interface ReportPdfProps {
  request: ServiceRequest & { category: ServiceCategory };
  report: Report;
  clientName: string;
  providerName: string;
}

function ReportDocument({ request, report, clientName, providerName }: ReportPdfProps) {
  const checklist = (report.checklistData as Record<string, unknown>) || {};
  const answers = (report.clientQuestionsAnswers as { question: string; answer: string }[]) || [];

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.brand}>Bokle</Text>
          <Text style={styles.subtitle}>
            {request.requestType === "check_am" ? "Help Me Check Am Report" : "Service Visit Report"}
          </Text>
        </View>

        <View style={styles.section}>
          <View style={styles.row}>
            <Text style={styles.label}>Category</Text>
            <Text style={styles.value}>{request.category.name}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Client</Text>
            <Text style={styles.value}>{clientName}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Checker / Provider</Text>
            <Text style={styles.value}>{providerName}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Location</Text>
            <Text style={styles.value}>{request.serviceAddress}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Submitted</Text>
            <Text style={styles.value}>{new Date(report.submittedAt).toLocaleString("en-NG")}</Text>
          </View>
          {report.overallAssessment && (
            <View style={styles.row}>
              <Text style={styles.label}>Overall Assessment</Text>
              <Text style={styles.value}>{report.overallAssessment}</Text>
            </View>
          )}
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Checklist</Text>
          {Object.entries(checklist).map(([key, val]) => (
            <View key={key} style={styles.checklistItem}>
              <Text style={styles.bullet}>•</Text>
              <Text style={styles.value}>
                {key}: {String(val)}
              </Text>
            </View>
          ))}
        </View>

        {answers.length > 0 && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>Client Questions</Text>
            {answers.map((qa, i) => (
              <View key={i} style={{ marginBottom: 6 }}>
                <Text style={{ fontWeight: 700 }}>{qa.question}</Text>
                <Text>{qa.answer}</Text>
              </View>
            ))}
          </View>
        )}

        {report.notes && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>Observations</Text>
            <Text>{report.notes}</Text>
          </View>
        )}

        {report.isConcernFlagged && (
          <View style={styles.section}>
            <Text style={{ color: "#DC2626", fontWeight: 700 }}>⚠ Concern flagged</Text>
            <Text>{report.concernNotes}</Text>
          </View>
        )}

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Photos ({report.photoUrls.length})</Text>
          <Text style={{ fontSize: 9, color: "#4A6B63" }}>
            View full-resolution photos in the Bokle app — this document lists them by reference only.
          </Text>
          {report.photoUrls.map((url, i) => (
            <Text key={i} style={{ fontSize: 8, color: "#8AADA5" }}>
              {i + 1}. {url}
            </Text>
          ))}
        </View>

        <Text style={styles.footer}>
          Generated by Bokle · This report reflects the checker&apos;s on-site observations only.
        </Text>
      </Page>
    </Document>
  );
}

export async function generateReportPdf(props: ReportPdfProps): Promise<Buffer> {
  return renderToBuffer(<ReportDocument {...props} />);
}
